library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where (Date = '1/2/2007' OR Date = '2/2/2007')", header  = TRUE, sep = ";")
png("plot1.png", width = 480, height = 480)
hist(data$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red")
dev.off()