library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where (Date = '1/2/2007' OR Date = '2/2/2007')", header  = TRUE, sep = ";")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data$x <- paste(data$Date, data$Time)
data$y <- strptime(data$x, format = "%Y-%m-%d %H:%M:%S")
png("plot3.png", width = 480, height = 480)
plot(data$y, data$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(data$y, data$Sub_metering_2, col = "red")
lines(data$y, data$Sub_metering_3, col = "blue")
legend(x = "topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1))
dev.off()