library(sqldf)
data <- read.csv.sql("household_power_consumption.txt", sql = "select * from file where (Date = '1/2/2007' OR Date = '2/2/2007')", header  = TRUE, sep = ";")
data$Date <- as.Date(data$Date, "%d/%m/%Y")
data$x <- paste(data$Date, data$Time)
data$y <- strptime(data$x, format = "%Y-%m-%d %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par(mfrow = c(2,2))
with(data, {
  plot(data$y, data$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power")
  plot(data$y, data$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
  plot(data$y, data$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
  lines(data$y, data$Sub_metering_2, col = "red")
  lines(data$y, data$Sub_metering_3, col = "blue")
  legend(x = "topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = c(1,1))
  plot(data$y, data$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
})
dev.off()